# Introduction to Machine Learning
---

# Chapter 1 Perceptron

## Exercise 1.1
<b>For the following formal neuron, given the values of inputs, weights and a
threshold as shown in the table below, find the weighted sum values and outputs.</b><br>
w1 = 2, w2 = 3, h = 2

| x1 | x2 | Sigma wx | y |
|----|----|----|----|
|0   |0   |0   |0   |
|0   |1   |3   |1   |
|1   |0   |2   |0   |
|1   |1   |5   |1   |


## Exercise 1.2
<b>For the following formal neuron, given the values of inputs, weights and a
threshold as shown in the table below, find the weighted sum values and outputs.</b><br>
w1 = -3, w2 = -5, h = -4

| x1 | x2 | Sigma wx | y |
|----|----|----|----|
|0   |0   |0   |1   |
|0   |1   |-5  |0   |
|1   |0   |-3  |1   |
|1   |1   |-8  |0   |


## Exercise 1.3
<b>For the following neuron, determine the weights and the threshold so that the
outputs 𝑦 for each input are as shown in the table below.</b><br>

| x1 | x2 | Sigma wx | y |
|----|----|----|----|
|0   |0   |0   |0   |
|0   |1   |2   |1   |
|1   |0   |1   |0   |
|1   |1   |3   |1   |

weight for x1 = 1

weight for x2 = 2

threshold = 1


## Exercise 1.4
<b>For the following formal neuron, given the values of inputs, weights and a
threshold as shown in the table below, find the weighted sum values and outputs.</b><br>
w1 = 2, w2 = 3, w3 = 1, h = 2


| x1 | x2 | x3 | Sigma wx | y |
|----|----|----|----|----|
|0   |0   |0   |0   |0   |
|0   |0   |1   |1   |0   |
|0   |1   |0   |3   |1   |
|0   |1   |1   |4   |1   |
|1   |0   |0   |2   |0   |
|1   |0   |1   |3   |1   |
|1   |1   |0   |5   |1   |
|1   |1   |1   |6   |1   |

## Exercise 1.5
<b>For the following formal neuron, given the values of inputs, weights and a
threshold as shown in the table below, find the weighted sum values and outputs.</b><br>
w1 = 2, w2 = -3, w3 = -1, h = -1

| x1 | x2 | x3 | Sigma wx | y |
|----|----|----|----|----|
|0   |0   |0   |0   |1   |
|0   |0   |1   |-1  |0   |
|0   |1   |0   |-3  |0   |
|0   |1   |1   |-4  |0   |
|1   |0   |0   |2   |1   |
|1   |0   |1   |1   |1   |
|1   |1   |0   |-1  |0   |
|1   |1   |1   |-2  |0   |

## Exercise 1.6
<b>For the following neuron, determine the weights and the threshold so that the
outputs 𝑦 for each input are as shown in the table below.</b><br>
<b>Can you find these values?</b><br>


| x1 | x2 | x3 | Sigma wx | y |
|----|----|----|----|----|
|0   |0   |0   |0   |0   |
|0   |0   |1   |1   |1   |
|0   |1   |0   |-2  |0   |
|0   |1   |1   |-1  |0   |
|1   |0   |0   |3   |1   |
|1   |0   |1   |4   |1   |
|1   |1   |0   |1   |1   |
|1   |1   |1   |2   |1   |

weight for x1 = 3

weight for x2 = -2

weight for x3 = 1

threshold = 0



## Example 1.2

In [34]:
import numpy as np

x = np.array([1, 0, 1])
w = np.array([2, 3, -1])
np.dot(x, w.T)

1

In [35]:
import numpy as np

x = np.array([1, 0, 1])
w = np.array([[2], [3], [-1]])
np.dot(x, w)

array([1])

## Example 1.3

In [36]:
a = 3
b = 2
print(a > b)

True


In [37]:
a = 2
b = 3
print(a > b)

False


## Exercise 1.7
Get the following dot product in Python or MATLAB.<br>
Note that the definition of row vectors and the definition of column vectors are
different in the program.<br>
Also check that you get an error when you try to calculate whose dimensions do
not match.<br>
(A) xw
(B) xw^t
(C) x^tw
(D) x^tw^t
<br>, where x = [3 5 1 6], w = [2 7 1 2]

In [38]:
import numpy as np

x = np.array([3, 5, 1, 6])
w = np.array([2, 7, 1, 2])
print(np.dot(x, w))
print(np.dot(x, w.T))
print(np.dot(x.T, w))
print(np.dot(x.T, w.T))

54
54
54
54


## Exercise 1.8
Perform the following comparison operations in Python or MATLAB.<br>
Check the results of vector to scalar and vector to vector comparisons.<br>
(A) a > b
(B) b > a
(C) x > a
(D) x > w
<br>, where a = 5, b = 3, x = [3 5 1 6], w = [2 7 1 2]

In [39]:
import numpy as np

a = 5
b = 3
x = np.array([3, 5, 1, 6])
w = np.array([2, 7, 1, 2])

(A) a > b

In [40]:
print(a > b)

True


(B) b > a

In [41]:
print(b > a)

False


(C) x > a

In [42]:
print(x > a)

[False False False  True]


(D) x > w

In [43]:
print(x > w)

[ True False False  True]


## Example 1.4

In [44]:
import numpy as np

x = np.array([1, 1, 0])
w = np.array([0.5, 1.0, 0.5])
h = 1

def formal_neuron(x, w, h):

    p = np.dot(x, w)
    y = p > h
    #cast from  boolean to integer
    return y.astype(np.int)

y = formal_neuron(x, w.T, h)
print(y)

1


## Exercise 1.9
Implement example1.4 in Pythons or MATLAB.<br>
Check the outputs where inputs, weights and a threshold are given as
follows by both hand calculation and Python or MATLAB scripts.<br>
w = [2, -1, 3], h = 1

In [45]:
import numpy as np

x = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])
w = np.array([2, -1, 3])
h = 1

y = formal_neuron(x, w.T, h)
print(y)

[0 1 0 1 1 1 0 1]


## Example 1.5

In [46]:
import numpy as np

x = np.array([[0,0,0],
              [0,0,1],
              [0,1,0],
              [0,1,1],
              [1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
w = np.array([0.5, 1.0, 0.5])
h = 1

def formal_neuron(x, w, h):

    p = np.dot(x, w)
    y = p > h
    #cast from boolean to integer
    return y.astype(np.int)

y = formal_neuron(x, w.T, h)
print(y)

[0 0 0 1 0 0 1 1]


## Exercise 1.10

In [47]:
import numpy as np
x = np.array([[1, 0, 1],
              [0, 1, 0],
              [1, 1, 1]])
w = np.array([0.6, -1.5, 1.0])
h = 1.0

y = formal_neuron(x, w.T, h)
print(y)

[1 0 0]


## Exercise 1.11

In [48]:
import numpy as np
x = np.array([[1, 0, 1, 1],
              [0, 0, 1, 0],
              [1, 0, 1, 0]])
w = np.array([0.5, 1, 1.5, 0])
h = 1.5

y = formal_neuron(x, w.T, h)
print(y)

[1 0 1]


## Example 1.6

In [49]:
import numpy as np

x=np.array([[0,0,0],
            [0,0,1],
            [0,1,0],
            [0,1,1],
            [1,0,0],
            [1,0,1],
            [1,1,0],
            [1,1,1]])
w = np.array([[0.5, 0.0],
              [1.0, 0.5],
              [0.5, 1.0]])
h = np.array([0.5, 1.0])

def formal_neuron(x, w, h):
  p = np.dot(x, w)
  y = p > h
  #convert boolean to integer
  return y.astype(np.int)
  
y = formal_neuron(x, w, h)
print(y)


[[0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]]


## Exercise 1.12

In [50]:
import numpy as np
x = np.array([[1, 0, 1],
              [0, 1, 0],
              [1, 1, 1],
              [0, 1, 1]])
w = np.array([[2, -1, 3],
              [0, 4, 1],
              [-4, 2, -2]])
h= np.array([2, 0, 1])

y = formal_neuron(x, w, h)
print(y)

[[0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 0]]


## Exercise1.13

In [51]:
import numpy as np
x = np.array([[0, 1, 1, 1],
              [0, 1, 0, 0],
              [1, 1, 0, 0]])
w = np.array([[-2, 0, 2, 2],
              [-1, 2, 1, -1],
              [4, -3, 1, 0],
              [1, 1, 0, -3]])
h = np.array([1, 0, 0, 2])

y = formal_neuron(x, w, h)
print(y)

[[1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]]


## Example 1.7

In [52]:
import numpy as np

class FormalNeuronLayer:
  def __init__(self, w, h):
    self.w = w
    self.h = h
    
  def forward(self, x):
    p = np.dot(x, self.w)
    y = p > self.h
    return y.astype(np.int)

x = np.array([[0,0,0],
              [0,0,1],
              [0,1,0],
              [0,1,1],
              [1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
w = np.array([[0.5, 0.0],
              [1.0, 0.5],
              [0.5, 1.0]])
h = np.array([0.5, 1.0])

formalNeuron = FormalNeuronLayer(w,h)
y = formalNeuron.forward(x)
print(y)

[[0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]]


## Exercise 1.14

In [53]:
import numpy as np

class FormalNeuronLayer:
  def __init__(self, w, h):
    self.w = w
    self.h = h
    
  def forward(self, x):
    p = np.dot(x, self.w)
    y = p > self.h
    return y.astype(np.int)
    
x = np.array([[0, 1, 1, 1],
              [0, 1, 0, 0],
              [1, 1, 0, 0]])
w = np.array([[-2, 0, 2, 2],
              [-1, 2, 1, -1],
              [4, -3, 1, 0],
              [1, 1, 0, -3]])
h = np.array([1, 0, 0, 2])

formalNeuron = FormalNeuronLayer(w,h)
y = formalNeuron.forward(x)
print(y)

[[1 0 1 0]
 [0 1 1 0]
 [0 1 1 0]]


## Example 1.8

In [54]:
import numpy as np

class FormalNeuronLayer:
  def __init__(self, w, h):
    self.w = w
    self.h = h
    
  def forward(self, x):
    p = np.dot(x, self.w)
    y = p > self.h
    return y.astype(np.int)

x = np.array([[0,0,0],
              [0,0,1],
              [0,1,0],
              [0,1,1],
              [1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
w = np.array([[0.5, 1.0, 1.0],
              [1.0, 0.5, 0.5],
              [0.5, 1.0, 0.0]])
h = np.array([0.5, 1.5, 1.0])
u = np.array([[1.0, 0.5],
              [0.5, 0.0],
              [0.0, 1.0]])
g = np.array([1.0, 0.0])

formalNeuron1 = FormalNeuronLayer(w,h)
formalNeuron2 = FormalNeuronLayer(u,g)
y = formalNeuron1.forward(x)
print(y)
z = formalNeuron2.forward(y)
print(z)

[[0 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 0]
 [1 1 0]
 [1 0 1]
 [1 1 1]]
[[0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]]


## Exercise 1.15

In [55]:
import numpy as np

class FormalNeuronLayer:
  def __init__(self, w, h):
    self.w = w
    self.h = h
    
  def forward(self, x):
    p = np.dot(x, self.w)
    y = p > self.h
    return y.astype(np.int)

x = np.array([[1, 1, 1],
              [0, 1, 0],
              [1, 0, 0],
              [1, 0, 1]])
w = np.array([[-2, 1, 0, 1],
              [0, 1, -2, -1],
              [1, 0, 1, 1]])
h = np.array([2, -1, 0, 1])
u = np.array([[4, 1],
              [2, 3],
              [0, 1],
              [3, 1]])
g = np.array([2, 4])

formalNeuron1 = FormalNeuronLayer(w, h)
formalNeuron2 = FormalNeuronLayer(u, g)
y = formalNeuron1.forward(x)
print(y)
z = formalNeuron2.forward(y)
print(z)

[[0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 1 1]]
[[0 0]
 [0 0]
 [0 0]
 [1 1]]


## Exercise 1.16

In [56]:
import numpy as np

class FormalNeuronLayer:
  def __init__(self, w, h):
    self.w = w
    self.h = h
    
  def forward(self, x):
    p = np.dot(x, self.w)
    y = p > self.h
    return y.astype(np.int)

x = np.array([[1, 1, 1, 1],
              [0, 1, 0, 0],
              [0, 1, 1, 0],
              [1, 0, 0, 0],
              [0, 0, 1, 1]])
w = np.array([[3, 2, 2, 0],
              [4, 1, 5, 2],
              [1, 0, 1, 4],
              [0, 1, 0, 1]])
h = np.array([2, 6, 1, 0])
u = np.array([[4, 1, 4, 3],
              [2, 3, 0, 1],
              [0, 1, 2, 4],
              [3, 1, 1, 2]])
g = np.array([1, 4, 3, 5])

formalNeuron1 = FormalNeuronLayer(w, h)
formalNeuron2 = FormalNeuronLayer(u, g)
y = formalNeuron1.forward(x)
print(y)
z = formalNeuron2.forward(y)
print(z)

[[1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 0]
 [0 0 0 1]]
[[1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 0 0]]
